UPDATE ASG.NWT.PRODUCT AS P
SET P.UNITCOST = (
    SELECT PF.UnitCost
    FROM ASG.NWT.PRODUCT_FRESH PF
    WHERE P."productID" = PF."Product ID"
)
WHERE EXISTS (
    SELECT 1
    FROM ASG.NWT.PRODUCT_FRESH PF
    WHERE P."productID" = PF."Product ID"
);
