UPDATE PRODUCT
SET UNITCOST = (
    SELECT PF.UnitCost
    FROM PRODUCT_FRESH PF
    WHERE PRODUCT.productID = PF.ProductID
)
WHERE EXISTS (
    SELECT 1
    FROM PRODUCT_FRESH PF
    WHERE PRODUCT.productID = PF.ProductID
);
