UPDATE ASG.NWT.PRODUCT
SET UNITCOST = (
    SELECT PF."UnitCost"
    FROM ASG.NWT.PRODUCT_FRESH PF
    WHERE "productID" = PF."product id"
)
WHERE EXISTS (
    SELECT 1
    FROM ASG.NWT.PRODUCT_FRESH PF
    WHERE "productID" = PF."product id"
);
